### ISSUE TITLE
Find a way to display equations

### ISSUE THREAD

**Issue by Szymongib** [ms-inf-projects/equations-editor#3]
Find a way to display equations in the form that is easy to parse to MathMl and/or LaTeX.

Dependent on #6

**Comment by kfurgol** [comment]
take a look at https://github.com/Khan/KaTeX

**Comment by kfurgol** [comment]
and http://mathlib.de/en/demos/MathML

**Comment by kfurgol** [comment]
and https://www.maths.nottingham.ac.uk/plp/pmadw/lm.html

**Comment by kfurgol** [comment]
and https://www.npmjs.com/package/mathml

**Comment by kfurgol** [comment]
We decided to write our mechanism in vue.js.
